### ISSUE TITLE
ERR_OUT_OF_RANGE('value', `>= ${min} and <= ${max}`, value)

### ISSUE THREAD

**Issue by Turboman533** [T-vK/Beats4Wled#1]
I was able to connect spotify and wled but keep on running into this error

RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 255. Received 256
    at writeU_Int8 (node:internal/buffer:740:11)
    at Buffer.writeUInt8 (node:internal/buffer:750:10)
    at WledRealtimeClient.update (file:///C:/Users/rohan/Downloads/Beats4Wled-main/lib/WledRealtimeClient.mjs:53:22)
    at Beats4Wled.wledSync (file:///C:/Users/rohan/Downloads/Beats4Wled-main/Beats4Wled.mjs:178:23)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ERR_OUT_OF_RANGE'

![Screenshot 2024-07-17 030446](https://github.com/user-attachments/assets/cfbf2309-b4d2-45b4-a37d-19953e733110)

**Comment by T-vK** [comment]
Probably a bug in lib/WledRealtimeClient.mjs that happens when the WLED segments are longer than 256 LEDs. I'll look into it when I can find some time.

**Comment by Turboman533** [comment]
I was able to fix it. Is their anyway I could send you the WledRealtimeClient.mjs file?

**Comment by T-vK** [comment]
Sure, if you know git, you could create a Pull Request. But you can also paste the file contents here if you want.

**Comment by Turboman533** [comment]
This is the fix for the WledRealtimeClient.mjs: 

import dgram from 'dgram';

export default class WledRealtimeClient {
    constructor(wledControllerIp, numPixels, udpPort = 21324, maxPixelsPerPacket = 126, maxFps = 0) {
        this.wledControllerIp = wledControllerIp;
        this.numPixels = numPixels;
        this.udpPort = udpPort;
        this.maxPixelsPerPacket = maxPixelsPerPacket;
        this.maxFps = maxFps;
        this.sock = dgram.createSocket('udp4');
        this.prevPixels = Buffer.alloc(3 * this.numPixels, 253);
        this.pixels = Buffer.alloc(3 * this.numPixels, 1);
        this.lastUpdateTime = 0;
    }

    update() {
        const currentTime = Date.now();
        const elapsed = currentTime - this.lastUpdateTime;
        const minInterval = 1000 / this.maxFps;

        if (this.maxFps > 0 && elapsed < minInterval) {
            return; // Skip update if it's too soon since the last one
        }

        this.lastUpdateTime = currentTime;

        // Truncate values and cast to integer
        for (let i = 0; i < this.pixels.length; i++) {
            this.pixels[i] = Math.max(0, Math.min(255, this.pixels[i]));
        }

        const p = Buffer.from(this.pixels);
        const idx = [];
        for (let i = 0; i < p.length; i += 3) {
            if (!this.areArraysEqual(p.slice(i, i + 3), this.prevPixels.slice(i, i + 3))) {
                idx.push(i / 3);
            }
        }

        const numPixels = idx.length;
        const nPackets = Math.ceil(numPixels / this.maxPixelsPerPacket);
        const idxSplit = [];
        for (let i = 0; i < nPackets; i++) {
            idxSplit.push(idx.slice(i * this.maxPixelsPerPacket, (i + 1) * this.maxPixelsPerPacket));
        }

        const header = Buffer.from([1, 2]); // WARLS protocol header
        for (const packetIndices of idxSplit) {
            const data = Buffer.alloc(header.length + packetIndices.length * 5); // 2 bytes for index + 3 bytes for RGB
            header.copy(data, 0);
            let dataIndex = header.length;
            for (const i of packetIndices) {
                data.writeUInt16BE(i, dataIndex); // Write 16-bit index
                dataIndex += 2;
                p.copy(data, dataIndex, i * 3, i * 3 + 3); // Copy RGB data
                dataIndex += 3;
            }
            if (!this.prevPixels.equals(Buffer.from(p))) {
                this.sock.send(data, 0, data.length, this.udpPort, this.wledControllerIp);
            }
        }

        this.prevPixels = Buffer.from(p);
    }

    areArraysEqual(arr1, arr2) {
        if (arr1.length !== arr2.length) {
            return false;
        }
        for (let i = 0; i < arr1.length; i++) {
            if (arr1[i] !== arr2[i]) {
                return false;
            }
        }
        return true;
    }

    setLeds(pixels) {
        for (let i = 0; i < pixels.length; i++) {
            const pixel = pixels[i];
            this.pixels[i * 3] = pixel[0]; // Red
            this.pixels[i * 3 + 1] = pixel[1]; // Green
            this.pixels[i * 3 + 2] = pixel[2]; // Blue
        }
    }
};

**Comment by T-vK** [comment]
Thank you for taking the time, I updated the file accordingly!
